apiVersion: v2
name: todo-app
description: A Helm chart for the Todo App
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: common
    version: "1.14.1"
    repository: "https://charts.bitnami.com/bitnami"